// GENERATED by tool/generate_grid_assets.dart — do not edit.
// Source of truth: the `grid:` block in packages/decisions_grid_assets/pubspec.yaml.
// Regenerate: dart run tool/generate_grid_assets.dart

/// The asset surface `decisions_grid_assets` vends, as the neutral
/// `grid_sdk` declaration contract.
library;

import 'package:grid_sdk/grid_sdk.dart';

/// The `decisions_grid_assets` asset pack.
abstract final class GridAssetsPack {
  /// The vending Dart package.
  static const String package = 'decisions_grid_assets';

  /// `decisions_grid_assets/rubric/decision-alignment`.
  static const GridAssetDefinition
  rubricDecisionAlignment = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'decision-alignment',
    ),
    description:
        'Grades a spec against the roster-wide union of decisions governing its touched surfaces.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: RequiresPath('docs/decisions'),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/decision-alignment.md',
      ),
    ],
  );

  /// `decisions_grid_assets/skill/decide`.
  static const GridAssetDefinition skillDecide = GridAssetDefinition(
    assetKey: AssetKey(package: package, kind: AssetKind.skill, id: 'decide'),
    description:
        'Record a placement, naming, seam, policy, or human ruling that has already been decided, with collision-safe identity, governed surfaces, honest authorship, correct edges, an optional minted decision bead, and first-write validation.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: RequiresPath('docs/decisions'),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/decide/SKILL.md',
      ),
    ],
  );

  /// `decisions_grid_assets/skill/ratify`.
  static const GridAssetDefinition skillRatify = GridAssetDefinition(
    assetKey: AssetKey(package: package, kind: AssetKind.skill, id: 'ratify'),
    description:
        'Hold a docket for one decision register - compute the four ratified trigger signals, present a bounded worksheet of the decisions needing a force change with a proposed disposition and its evidence, and record every ruling as an entry plus its force operation.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: RequiresPath('docs/decisions'),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/ratify/SKILL.md',
      ),
    ],
  );

  /// Every declared asset, in declaration order.
  static const List<GridAssetDefinition> assets = <GridAssetDefinition>[
    rubricDecisionAlignment,
    skillDecide,
    skillRatify,
  ];

  /// The validated pack. Built, not `const`: the collections
  /// validate duplicates at construction
  /// (`the_grid#asset-definitions-are-const-collections-are-validated`).
  static final GridAssetPackDefinition definition = GridAssetPackDefinition(
    package: package,
    assets: assets,
  );

  /// This pack's overlay head → target mappings.
  static const Map<String, String> stationOverlayMappings = <String, String>{
    'claude': '.claude',
  };
}
